#!/usr/bin/env python3
"""env_snapshot.py

Author: cbwinslow
Date: 2025-11-16

Summary:
    Capture a snapshot of the current machine's hardware and software environment
    to serve as an "opening balance sheet" for a project or AI agent.

Inputs:
    - Optional CLI arguments:
        --output / -o : Path to write JSON snapshot (default: ./env_snapshot.json)

Outputs:
    - JSON file containing:
        - OS info
        - CPU info
        - Memory info
        - Disk usage summary
        - GPU info (if detectable via nvidia-smi or common paths)
        - Python version & installed packages (short summary)
        - Timestamp and hostname

Usage:
    python env_snapshot.py
    python env_snapshot.py --output snapshots/env_snapshot.json

Notes:
    - Designed to be safe and read-only.
    - Tries to gather as much info as possible without failing if any single probe fails.
    - Logs warnings instead of crashing when a subsystem is unavailable.

Modification Log:
    - 2025-11-16 : Initial version generated by AI assistant.
"""


import argparse
import json
import os
import platform
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional


def safe_run(cmd: List[str]) -> Optional[str]:
    """Run a command safely, returning stdout as text or None on failure."""
    try:
        completed = subprocess.run(
            cmd, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
        )
        if completed.returncode != 0:
            return None
        return completed.stdout.strip()
    except Exception:
        return None


def get_os_info() -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    try:
        data["system"] = platform.system()
        data["release"] = platform.release()
        data["version"] = platform.version()
        data["platform"] = platform.platform()
        data["machine"] = platform.machine()
        data["python_version"] = platform.python_version()
    except Exception as exc:
        data["error"] = f"Failed to gather OS info: {exc}"
    return data


def get_cpu_info() -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    try:
        data["processor"] = platform.processor()
        data["architecture"] = platform.machine()
        data["cores_logical"] = os.cpu_count()
    except Exception as exc:
        data["error"] = f"Failed to gather CPU info: {exc}"
    return data


def get_memory_info() -> Dict[str, Any]:
    """Use psutil if available; fall back to /proc/meminfo on Linux."""
    data: Dict[str, Any] = {}
    try:
        import psutil  # type: ignore

        vmem = psutil.virtual_memory()
        data["total"] = vmem.total
        data["available"] = vmem.available
        data["used"] = vmem.used
        data["percent"] = vmem.percent
    except Exception:
        try:
            meminfo_path = Path("/proc/meminfo")
            if meminfo_path.exists():
                raw: Dict[str, Any] = {}
                for line in meminfo_path.read_text().splitlines():
                    if ":" in line:
                        key, val = line.split(":", 1)
                        raw[key.strip()] = val.strip()
                data["raw"] = raw
        except Exception as exc:
            data["error"] = f"Failed to gather memory info: {exc}"
    return data


def get_disk_info() -> Dict[str, Any]:
    data: Dict[str, Any] = {"mounts": []}
    try:
        from shutil import disk_usage

        for path in ["/", str(Path.home())]:
            try:
                usage = disk_usage(path)
                data["mounts"].append(
                    {
                        "path": path,
                        "total": usage.total,
                        "used": usage.used,
                        "free": usage.free,
                    }
                )
            except Exception:
                continue
    except Exception as exc:
        data["error"] = f"Failed to gather disk info: {exc}"
    return data


def get_gpu_info() -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    nvidia_smi = shutil.which("nvidia-smi")
    if nvidia_smi:
        out = safe_run(
            [
                nvidia_smi,
                "--query-gpu=name,memory.total,memory.free",
                "--format=csv,noheader,nounits",
            ]
        )
        if out:
            gpus = []
            for line in out.splitlines():
                parts = [p.strip() for p in line.split(",") if p.strip()]
                if len(parts) >= 3:
                    gpus.append(
                        {
                            "name": parts[0],
                            "memory_total_mb": parts[1],
                            "memory_free_mb": parts[2],
                        }
                    )
            data["nvidia_smi"] = gpus
    return data


def get_python_packages(limit: int = 50) -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    try:
        from importlib.metadata import distributions  # type: ignore

        pkgs = []
        for dist in distributions():
            name = dist.metadata.get("Name") or "<unknown>"
            pkgs.append({"name": name, "version": dist.version})
            if len(pkgs) >= limit:
                break
        data["packages_preview"] = pkgs
        data["note"] = f"Showing up to {limit} installed packages."
    except Exception as exc:
        data["error"] = f"Failed to list Python packages: {exc}"
    return data


def build_snapshot() -> Dict[str, Any]:
    snapshot: Dict[str, Any] = {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "hostname": socket.gethostname(),
    }
    snapshot["os"] = get_os_info()
    snapshot["cpu"] = get_cpu_info()
    snapshot["memory"] = get_memory_info()
    snapshot["disk"] = get_disk_info()
    snapshot["gpu"] = get_gpu_info()
    snapshot["python"] = get_python_packages()
    return snapshot


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Capture a JSON snapshot of the current environment (hardware & software)."
    )
    parser.add_argument(
        "-o",
        "--output",
        default="env_snapshot.json",
        help="Output JSON file path (default: env_snapshot.json)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = Path(args.output).expanduser().resolve()
    snapshot = build_snapshot()

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as f:
            json.dump(snapshot, f, indent=2, sort_keys=True)
        print(f"[env_snapshot] Wrote environment snapshot to: {output_path}")
    except Exception as exc:
        print(
            f"[env_snapshot] ERROR: failed to write snapshot to {output_path}: {exc}",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
